#!/usr/bin/env python3
"""
Installation script for LLDB Objective-C Tools.

This script manages the .lldbinit file to automatically load the Objective-C
debugging commands when LLDB starts.

Usage:
    ./install.py            # Install to ~/.lldbinit
    ./install.py --uninstall # Remove from ~/.lldbinit
    ./install.py --status    # Check installation status
"""

import os
import sys
import argparse
from pathlib import Path

# Import version
try:
    from version import __version__
except ImportError:
    __version__ = "unknown"

# Configuration
SCRIPT_DIR = Path(__file__).parent.absolute()
LLDBINIT_PATH = Path.home() / ".lldbinit"

# Marker comments for our block in .lldbinit
MARKER_START = "# BEGIN lldb-objc auto-generated section"
MARKER_END = "# END lldb-objc auto-generated section"


def get_lldbinit_commands():
    """Generate the commands to add to .lldbinit."""
    commands = [
        MARKER_START,
        f"# LLDB Objective-C Tools v{__version__}",
        f"# Auto-generated by install.py - DO NOT EDIT THIS SECTION",
        f"command script import {SCRIPT_DIR / 'objc_breakpoint.py'}",
        f"command script import {SCRIPT_DIR / 'objc_find.py'}",
        f"command script import {SCRIPT_DIR / 'objc_classes.py'}",
        MARKER_END,
    ]
    return "\n".join(commands) + "\n"


def read_lldbinit():
    """Read the current .lldbinit file."""
    if not LLDBINIT_PATH.exists():
        return ""
    return LLDBINIT_PATH.read_text()


def write_lldbinit(content):
    """Write content to .lldbinit file."""
    # Create backup
    if LLDBINIT_PATH.exists():
        backup_path = LLDBINIT_PATH.with_suffix(".lldbinit.backup")
        LLDBINIT_PATH.rename(backup_path)
        print(f"Created backup: {backup_path}")

    LLDBINIT_PATH.write_text(content)
    print(f"Updated: {LLDBINIT_PATH}")


def remove_existing_section(content):
    """Remove any existing lldb-objc section from .lldbinit."""
    lines = content.split("\n")
    result = []
    in_section = False

    for line in lines:
        if line.strip() == MARKER_START:
            in_section = True
            continue
        elif line.strip() == MARKER_END:
            in_section = False
            continue

        if not in_section:
            result.append(line)

    # Remove trailing empty lines but keep one if file is not empty
    while len(result) > 1 and result[-1].strip() == "":
        result.pop()

    return "\n".join(result)


def install():
    """Install the LLDB commands to .lldbinit."""
    print(f"Installing LLDB Objective-C Tools v{__version__}...")
    print(f"Script directory: {SCRIPT_DIR}")
    print(f"Target file: {LLDBINIT_PATH}")

    # Verify scripts exist
    scripts = [
        SCRIPT_DIR / "objc_breakpoint.py",
        SCRIPT_DIR / "objc_find.py",
        SCRIPT_DIR / "objc_classes.py",
        SCRIPT_DIR / "version.py",
    ]

    for script in scripts:
        if not script.exists():
            print(f"Error: Required file not found: {script}", file=sys.stderr)
            return False

    # Read existing .lldbinit
    content = read_lldbinit()

    # Remove any existing section
    content = remove_existing_section(content)

    # Add newline before our section if file is not empty
    if content.strip():
        content = content.rstrip() + "\n\n"

    # Append our commands
    content += get_lldbinit_commands()

    # Write back
    write_lldbinit(content)

    print("\nInstallation complete!")
    print("\nThe following commands are now available in LLDB:")
    print("  obrk     - Set breakpoints on Objective-C methods")
    print("  ofind    - Find selectors in Objective-C classes")
    print("  oclasses - Find Objective-C classes by pattern")
    print("\nStart LLDB to use the commands.")

    return True


def uninstall():
    """Remove the LLDB commands from .lldbinit."""
    print(f"Uninstalling LLDB Objective-C Tools...")
    print(f"Target file: {LLDBINIT_PATH}")

    if not LLDBINIT_PATH.exists():
        print("No .lldbinit file found. Nothing to uninstall.")
        return True

    # Read existing .lldbinit
    content = read_lldbinit()

    # Check if our section exists
    if MARKER_START not in content:
        print("LLDB Objective-C Tools not found in .lldbinit")
        return True

    # Remove our section
    content = remove_existing_section(content)

    # Write back
    write_lldbinit(content)

    print("Uninstallation complete!")

    return True


def check_status():
    """Check if the tools are installed."""
    print(f"LLDB Objective-C Tools v{__version__}")
    print(f"Script directory: {SCRIPT_DIR}")
    print(f"Target file: {LLDBINIT_PATH}")
    print()

    if not LLDBINIT_PATH.exists():
        print("Status: NOT INSTALLED (.lldbinit does not exist)")
        return

    content = read_lldbinit()

    if MARKER_START in content:
        print("Status: INSTALLED")
        print("\nCurrent configuration in .lldbinit:")

        # Extract and display our section
        lines = content.split("\n")
        in_section = False
        for line in lines:
            if line.strip() == MARKER_START:
                in_section = True
            if in_section:
                print(f"  {line}")
            if line.strip() == MARKER_END:
                break
    else:
        print("Status: NOT INSTALLED")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description=f"Install LLDB Objective-C Tools v{__version__}",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  ./install.py              Install to ~/.lldbinit
  ./install.py --uninstall  Remove from ~/.lldbinit
  ./install.py --status     Check installation status
        """
    )

    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--uninstall",
        action="store_true",
        help="Remove LLDB Objective-C Tools from .lldbinit"
    )
    group.add_argument(
        "--status",
        action="store_true",
        help="Check installation status"
    )

    args = parser.parse_args()

    try:
        if args.uninstall:
            success = uninstall()
        elif args.status:
            check_status()
            success = True
        else:
            success = install()

        sys.exit(0 if success else 1)

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
